server.port: 9080

spring:
  application:
    name: LexServerApplication
  datasource:
    url: jdbc:h2:mem:lex-test-app;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  activemq:
    broker-url: tcp://${DOCKER_IP:localhost}:61616
    user: admin
    password: admin
    in-memory: false

camunda:
  bpm:
    admin-user:
      id: admin
